### ISSUE TITLE
Any updates planned?

### ISSUE THREAD

**Issue by ttodua** [NitrusAphalion/ninja-tools#2]
This is not being opened in VS 2022.
also, even after manually opening csproj, build fails: 
`Could not copy the file "..\ninja-tools-master\NinjaTools\sqlceca40.dll" because it was not found.` 
and similarly, several other files too.

otherwise seems useful.

**Comment by ttodua** [comment]
_update: seems those .dll files reside somewhere in installed packages folders, and need to manually copy from there..._

**Comment by NitrusAphalion** [comment]
No updates planned for now. I did give it a quick run in VS 2022 and ran into some issues which I committed change for.

For VS 2022 you will need the following:

- https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects
- https://www.microsoft.com/en-us/download/details.aspx?id=30709
